### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by machawk1** [edsu/spn#1]
Thanks for putting this on GitHub @edsu!

Can you add a license to the repo for anyone that wants to reuse or extend the code?

**Comment by edsu** [comment]
Sure Mat! Actually would you be willing to do a call with us to chat about this stuff sometime?

**Comment by machawk1** [comment]
Sure thing, Ed. Shoot me an e-mail and we can discuss topics and times.

Closed with 19b524e8445b8402977c4f10beb149fe703be035.
